/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg2;

import javax.swing.JFrame;

/**
 *
 * @author cindy
 */
public class MenuCategory extends javax.swing.JFrame {
String uname;
    /**
     * Creates new form MenuCategory
     */
    public MenuCategory(String uname) {
        initComponents();
        this.uname = uname;
    }

     public MenuCategory() {
        initComponents();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fav = new javax.swing.JButton();
        appetizer = new javax.swing.JButton();
        sashimi = new javax.swing.JButton();
        gunkan = new javax.swing.JButton();
        makimono = new javax.swing.JButton();
        temaki = new javax.swing.JButton();
        noodles = new javax.swing.JButton();
        yakitori = new javax.swing.JButton();
        drinks = new javax.swing.JButton();
        dessert = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 1350));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(607, 0, 0, 0);

        fav.setBorder(null);
        fav.setContentAreaFilled(false);
        fav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                favActionPerformed(evt);
            }
        });
        getContentPane().add(fav);
        fav.setBounds(20, 80, 250, 110);

        appetizer.setBorder(null);
        appetizer.setContentAreaFilled(false);
        appetizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appetizerActionPerformed(evt);
            }
        });
        getContentPane().add(appetizer);
        appetizer.setBounds(20, 200, 250, 110);

        sashimi.setBorder(null);
        sashimi.setContentAreaFilled(false);
        sashimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sashimiActionPerformed(evt);
            }
        });
        getContentPane().add(sashimi);
        sashimi.setBounds(20, 320, 250, 110);

        gunkan.setBorder(null);
        gunkan.setContentAreaFilled(false);
        gunkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gunkanActionPerformed(evt);
            }
        });
        getContentPane().add(gunkan);
        gunkan.setBounds(20, 430, 250, 110);

        makimono.setBorder(null);
        makimono.setContentAreaFilled(false);
        makimono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makimonoActionPerformed(evt);
            }
        });
        getContentPane().add(makimono);
        makimono.setBounds(20, 550, 250, 120);

        temaki.setBorder(null);
        temaki.setContentAreaFilled(false);
        temaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temakiActionPerformed(evt);
            }
        });
        getContentPane().add(temaki);
        temaki.setBounds(20, 670, 250, 100);

        noodles.setBorder(null);
        noodles.setContentAreaFilled(false);
        noodles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noodlesActionPerformed(evt);
            }
        });
        getContentPane().add(noodles);
        noodles.setBounds(20, 780, 250, 110);

        yakitori.setBorder(null);
        yakitori.setContentAreaFilled(false);
        yakitori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yakitoriActionPerformed(evt);
            }
        });
        getContentPane().add(yakitori);
        yakitori.setBounds(20, 900, 250, 110);

        drinks.setBorder(null);
        drinks.setContentAreaFilled(false);
        drinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinksActionPerformed(evt);
            }
        });
        getContentPane().add(drinks);
        drinks.setBounds(20, 1020, 250, 110);

        dessert.setBorder(null);
        dessert.setContentAreaFilled(false);
        dessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dessertActionPerformed(evt);
            }
        });
        getContentPane().add(dessert);
        dessert.setBounds(20, 1130, 240, 120);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\cindy\\Downloads\\Final Project programming\\front end delivery\\home page.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 280, 1258);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void favActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_favActionPerformed
        // TODO add your handling code here:
        Favorite fav = new Favorite (uname);
        fav.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_favActionPerformed

    private void dessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dessertActionPerformed
        // TODO add your handling code here:
        Dessert ds = new Dessert ();
        ds.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_dessertActionPerformed

    private void appetizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appetizerActionPerformed
        // TODO add your handling code here:
        Appetizer app = new Appetizer ();
        app.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_appetizerActionPerformed

    private void sashimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sashimiActionPerformed
        // TODO add your handling code here:
        Sashimi ss = new Sashimi ();
        ss.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sashimiActionPerformed

    private void gunkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gunkanActionPerformed
        // TODO add your handling code here:
        Gunkan gk = new Gunkan ();
        gk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gunkanActionPerformed

    private void makimonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makimonoActionPerformed
        // TODO add your handling code here:
        Makimono mk = new Makimono ();
        mk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_makimonoActionPerformed

    private void temakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temakiActionPerformed
        // TODO add your handling code here:
        Temaki tm = new Temaki ();
        tm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_temakiActionPerformed

    private void noodlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noodlesActionPerformed
        // TODO add your handling code here:
        Noodles nd = new Noodles ();
        nd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_noodlesActionPerformed

    private void yakitoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yakitoriActionPerformed
        // TODO add your handling code here:
        Yakitori yk = new Yakitori ();
        yk.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_yakitoriActionPerformed

    private void drinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinksActionPerformed
        // TODO add your handling code here:
        Drinks dr = new Drinks ();
        dr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_drinksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCategory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JFrame menuCategory = new MenuCategory();
                menuCategory.setVisible(true);
                menuCategory.setSize(500,800);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appetizer;
    private javax.swing.JButton dessert;
    private javax.swing.JButton drinks;
    private javax.swing.JButton fav;
    private javax.swing.JButton gunkan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton makimono;
    private javax.swing.JButton noodles;
    private javax.swing.JButton sashimi;
    private javax.swing.JButton temaki;
    private javax.swing.JButton yakitori;
    // End of variables declaration//GEN-END:variables
}
